version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: beedoo-nginx
        ports:
            - '80:80'
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app

    app:
        container_name: beedoo-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        container_name: beedoo-mysql
        ports:
            - '3306:3306'
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: beedoo
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:

